resources:
  - url: http://127.0.0.1:5000/shopping-list-card.js
    type: module
views:
  - cards:
      - type: custom:shopping-list-card
        name: Boilerplate Card Development
        entity: sun.sun
        test_gui: true
