name: "Build"

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Push latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          yarn
          yarn build
