name: "Build"

on:
  push:
    branches:
      - master

jobs:
  latest:
    name: Push latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          yarn
          yarn build

      - name: Copy dist for release
        run: cp  /home/runner/work/shopping-list-card/shopping-list-card/dist/shopping-list-card.js  /home/runner/work/shopping-list-card/shopping-list-card/shopping-list-card.js

      - name: Commit dist file
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Andrew Smith
          author_email: andrew@andrew.codes
          message: Release
          add: "./shopping-list-card.js"
          tag: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
