name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/shopping-list-card/shopping-list-card
          yarn
          yarn build

      - name: Copy dist for release
        run: cp  /home/runner/work/shopping-list-card/shopping-list-card/dist/shopping-list-card.js  /home/runner/work/shopping-list-card/shopping-list-card/shopping-list-card.js

      - name: Commit dist file
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Andrew Smith
          author_email: andrew@andrew.codes
          message: Release
          add: "./shopping-list-card.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
