name: Release

on:
  create:
    tags:
      - "v*"

jobs:
  release:
    name: Published release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/shopping-list-card/shopping-list-card
          yarn
          yarn build

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/shopping-list-card/shopping-list-card/dist/shopping-list-card.js
          asset_name: shopping-list-card.js
          tag: ${{ github.ref }}
          overwrite: true

      - name: Copy dist for release
        run: cp  /home/runner/work/shopping-list-card/shopping-list-card/dist/shopping-list-card.js  /home/runner/work/shopping-list-card/shopping-list-card/shopping-list-card.js

      - name: Commit dist file
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Andrew Smith
          author_email: andrew@andrew.codes
          message: Release
          add: "./shopping-list-card.js"
          tag: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
